num = input("Please tell me your age: ")
print(f"You are currently {num} years old.")
print(f"In 10 years. you'll be {int(num) + 10} years old.")
print(f"In 20 years. you'll be {int(num) + 20} years old.")
print(f"In 30 years. you'll be {int(num) + 30} years old.")